### ISSUE TITLE
Running and Stopped container instances duplicated in Dashboard

### ISSUE THREAD

**Issue by lastcoolnameleft** [Microsoft/OMS-docker#70]
I'm running OMS-Docker on Minikube and see incorrect counts for Running and Stopped containers:

NOTE:  I'm using Minikube; however, I don't think that should matter.

* Create a new MiniKube instance
* Install Nginx
* Install oms-docker.yml
* Verify Container status is updated
* kubectl delete po/omsagent  (Some logs were not going to OMS, so I tried to restart to see if that fixed it)
* Search for: "ContainerInventory | where ContainerState == "Running" | summarize AggregatedValue = count() by Computer, Image"
* Should see two instances.

8/24/2017 7:16:55.443 PM | ContainerInventory 
...TimeGenerated:8/24/2017 7:16:55.443 PM
...Computer:minikube
...Name:k8s_nginx_nginx-4217019353-fh659_default_3b3d418a-891c-11e7-85c8-0800277bef1c_0
...ContainerHostname:nginx-4217019353-fh659
...Image:nginx
...ImageTag:latest
...ContainerState:Running
...Ports:null
...ExitCode:0
...EnvironmentVar:["KUBERNETES_SERVICE_PORT=443", "KUBERNETES_SERVICE_PORT_HTTPS=443", "KUBERNETES_PORT=tcp://10.0.0.1:443", "KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443", "KUBERNETES_PORT_443_TCP_PROTO=tcp", "KUBERNETES_PORT_443_TCP_PORT=443", "KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1", "KUBERNETES_SERVICE_HOST=10.0.0.1", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "NGINX_VERSION=1.13.3-1~stretch", "NJS_VERSION=1.13.3.0.1.11-1~stretch"]
...Command:["nginx", "-g", "daemon off "]
...CreatedTime:8/24/2017 5:33:32.114 PM
...StartedTime:8/24/2017 5:33:32.200 PM
...FinishedTime:12/31/0000 6:00:00.000 PM
...Type:ContainerInventory
...TenantId:ada812eb-67e3-44e2-8da8-11c31fd741a1
...SourceSystem:Containers
...ContainerID:d14a9111af4ff912fa2befdd028ef65c6491e02849a39e3c60860829ac91423c
...ImageID:sha256:b8efb18f159bd948486f18bd8940b56fd2298b438229f5bd2bcf4cedcf037448
[-] show less
8/24/2017 8:09:55.007 PM | ContainerInventory 
...TimeGenerated:8/24/2017 8:09:55.007 PM
...Computer:minikube
...Name:k8s_nginx_nginx-4217019353-fh659_default_3b3d418a-891c-11e7-85c8-0800277bef1c_0
...ContainerHostname:nginx-4217019353-fh659
...Image:nginx
...ImageTag:latest
...ContainerState:Running
...Ports:null
...ExitCode:0
...EnvironmentVar:["KUBERNETES_SERVICE_PORT=443", "KUBERNETES_SERVICE_PORT_HTTPS=443", "KUBERNETES_PORT=tcp://10.0.0.1:443", "KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443", "KUBERNETES_PORT_443_TCP_PROTO=tcp", "KUBERNETES_PORT_443_TCP_PORT=443", "KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1", "KUBERNETES_SERVICE_HOST=10.0.0.1", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "NGINX_VERSION=1.13.3-1~stretch", "NJS_VERSION=1.13.3.0.1.11-1~stretch"]
...Command:["nginx", "-g", "daemon off "]
...CreatedTime:8/24/2017 5:33:32.114 PM
...StartedTime:8/24/2017 5:33:32.200 PM
...FinishedTime:12/31/0000 6:00:00.000 PM
...Type:ContainerInventory
...TenantId:ada812eb-67e3-44e2-8da8-11c31fd741a1
...SourceSystem:Containers
...ContainerID:d14a9111af4ff912fa2befdd028ef65c6491e02849a39e3c60860829ac91423c
...ImageID:sha256:b8efb18f159bd948486f18bd8940b56fd2298b438229f5bd2bcf4cedcf037448
[-] show less

**Comment by lastcoolnameleft** [comment]
To be clear, the list of # of running and stopped containers doubled after the steps above.

**Comment by keikhara** [comment]
@lastcoolnameleft we've pushed an update to fix the UI. Can you look at it again?

**Comment by srhhyd** [comment]
I am experiencing the same issue when I create a OMS-Docker container on COREOS. I see container instances duplicated in the dashboard

**Comment by srhhyd** [comment]
@keikhara I still experiencing the same problem when I create a OMS-agent as a docker container in Core OS vm.

**Comment by srhhyd** [comment]
I am seeing docker container as a computer in the azure console

**Comment by keikhara** [comment]
@lastcoolnameleft Please try the latest agent. If you have any issues, please reactive this.
